

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - local
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - local
  backend:
    build:
      context: ./server
      dockerfile: apps/server/Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    networks:
      - local

  frontend:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    depends_on:
      - backend
    networks:
      - local
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - local
    depends_on:
      - backend
      - frontend
networks:
  local:
volumes:
  pgdata:
